name: MCCreativeLabExtension
main: de.verdox.mccreativelab.MCCreativeLabExtension
description: The mccreativelab implementation of mcc-wrapper loaded via this plugin
load: STARTUP

bootstrapper: de.verdox.mccreativelab.PluginBootstrap
loader: de.verdox.mccreativelab.PluginBootstrap

version: '1.21.1-R0.1-SNAPSHOT'
api-version: '1.21.1'

commands:
  fakeblock:
    description: "Fake Block command"
  debug:
    description: "Debug command"